from BaseClasses import Location

class RustedMossLocation(Location):
    game: str = "Rusted Moss"


location_list = [
    "Flatlands Grappling Hook",
    "Flatlands Titania Piece",
    "Flatlands HP Overload",
    "Flatlands Thorny Wings",
    "Flatlands Time Manipulator",
    "Flatlands HP UP (Bottom)",
    "Flatlands HP UP (Top Left)",
    "Flatlands HP UP (Top Right)",
    "Flatlands MP UP (Bottom Left)",
    "Flatlands MP UP (Top Right)",
    "Flatlands TP UP",
    "Factory Roof Pistol",
    "Factory Roof Charge Jump",
    "Factory Roof Thorny Rose",
    "Factory Roof Giant Chambers",
    "Factory Roof Magnet",
    "Factory Roof Spiced Gunpowder",
    "Factory Roof Erosive Bullets",
    "Factory Roof MP UP",
    "Factory Roof TP UP (Bottom Left)",
    "Factory Roof TP UP (Middle)",
    "Factory Roof TP UP (Top Right)",
    "Snowy Outpost Grenade",
    "Snowy Outpost Energy Disruptor",
    "Smoked Forest Sniper",
    "Smoked Forest Titania Piece",
    "Smoked Forest Short Fuse",
    "Smoked Forest Sprite's Breath",
    "Smoked Forest Titania's Protection",
    "Smoked Forest Powdered Nightshade",
    "Smoked Forest HP UP",
    "Smoked Forest MP UP",
    "Smoked Forest TP UP",
    "Smoked Forest Fae Silver (Bottom Left)",
    "Smoked Forest Fae Silver (Top Right)",
    "Mountainside Titania Piece",
    "Mountainside Energy Refiner",
    "Mountainside Ruby Slippers",
    "Mountainside Guardian Fae",
    "Mountainside HP UP",
    "Mountainside MP UP (Top)",
    "Mountainside MP UP (Bottom)",
    "Mountainside Fae Silver (Top)",
    "Mountainside Fae Silver (Bottom)",
    "Lab Titania Piece",
    "Lab Maya's Trinket",
    "Lab Rusted Coin",
    "Lab Fae of Love",
    "Lab Fae Silver (Left)",
    "Lab Fae Silver (Middle)",
    "Lab Fae Silver (Right)",
    "Ichor Refinery Shotgun",
    "Ichor Refinery Titania Piece",
    "Ichor Refinery Cleansing Charm",
    "Ichor Refinery Tattered Blindfold",
    "Ichor Refinery MP UP",
    "Ichor Refinery TP UP",
    "Ichor Refinery Fae Silver (Top Left)",
    "Ichor Refinery Fae Silver (Bottom Right)",
    "Living Quarters Bolt Dispenser",
    "Living Quarters Grappling Hook Upgrade", # Requires 4 titania pieces
    "Living Quarters Titania Piece",
    "Living Quarters Titania Piece (Head)",
    "Living Quarters Lucky Clover Pearl",
    "Living Quarters Cracked Monocle",
    "Living Quarters Wing Clipper",
    "Living Quarters HP UP",
    "Living Quarters MP UP",
    "Living Quarters TP UP",
    "Living Quarters Fae Silver (Top Right)",
    "Living Quarters Fae Silver (Bottom Left)",
    "Lake Rocket Launcher",
    "Lake Titania Piece",
    "Lake Fae of Glass",
    "Lake Magnetic Bullets",
    "Lake Dandelion Bomb",
    "Lake Fae of Hate",
    "Lake MP UP",
    "Lake TP UP",
    "Lake Fae Silver (Left)",
    "Lake Fae Silver (Right)",
    "Barrows Ceiling Cricket Bone Whip",
    "Barrows Ceiling Incendiary Essence",
    "Barrows Ceiling HP UP",
    "Barrows Ceiling TP UP",
    "Barrows Ceiling Fae Silver",
    "Elfame Infinite Grapple",
    "Elfame Fern's Trinket",
    "Elfame Fairy Ointment",
    "Elfame Powdered Fae Silver",
    "Elfame Heavy Ammo",
    "Elfame Fae Silver (Left)",
    "Elfame Fae Silver (Middle)",
    "Elfame Fae Silver (Right)",
]