gameLocationToLocationName = {
    "pickup_hp_rm_test_hidden": "Flatlands HP UP (Bottom)",
    "pickup_hp_rm_test_hidden_3": "Flatlands HP UP (Top Left)",
    "pickup_hp_rm_test_before_boss_alt": "Flatlands HP UP (Top Right)",
    "pickup_hp_rm_mount_4_half_right": "Smoked Forest HP UP",
    "pickup_hp_rm_forest_cafe_3": "Living Quarters HP UP",
    "pickup_hp_rm_sea_extra_2": "Mountainside HP UP",
    "pickup_hp_rm_underhang_b20": "Barrows Ceiling HP UP",
    "pickup_mp_rm_lake_hidden_3": "Lake MP UP",
    "pickup_mp_rm_forest_extra_3": "Living Quarters MP UP",
    "pickup_mp_rm_sea_left_2": "Mountainside MP UP (Bottom)",
    "pickup_mp_rm_catacombs_extra_1": "Ichor Refinery MP UP",
    "pickup_mp_rm_sea_2": "Mountainside MP UP (Top)",
    "pickup_mp_rm_moss_hidden_1": "Factory Roof MP UP",
    "pickup_mp_rm_4_hidden": "Flatlands MP UP (Top Right)",
    "pickup_mp_rm_mount_intro_begin": "Smoked Forest MP UP",
    "pickup_mp_rm_test_alt_alt": "Flatlands MP UP (Bottom Left)",
    "pickup_tp_rm_moss_8": "Factory Roof TP UP (Top Right)",
    "pickup_tp_rm_lake_hidden_4": "Lake TP UP",
    "pickup_tp_rm_forest_extra_0": "Living Quarters TP UP",
    "pickup_tp_rm_hidden_4": "Flatlands TP UP",
    "pickup_tp_rm_catacombs_extra_3": "Ichor Refinery TP UP",
    "pickup_tp_rm_moss_3": "Factory Roof TP UP (Middle)",
    "pickup_tp_rm_mount_10_alt": "Smoked Forest TP UP",
    "pickup_tp_rm_underhang_extra_2": "Barrows Ceiling TP UP",
    "pickup_tp_rm_moss_top_cave": "Factory Roof TP UP (Bottom Left)",
    "pickup_weapon_rm_moss_top_cave": "Factory Roof Pistol",
    "pickup_weapon_rm_catacombs_right_extra": "Ichor Refinery Shotgun",
    "pickup_weapon_rm_forest_extra_4": "Living Quarters Bolt Dispenser",
    "pickup_weapon_rm_lake_hidden_2": "Lake Rocket Launcher",
    "pickup_weapon_rm_mount_top_boss": "Smoked Forest Sniper",
    "pickup_flag_rm_forest_to_rain": "Living Quarters Flag",
    "pickup_flag_rm_mount_4_half_right": "Factory Roof Flag",
    "pickup_flag_rm_catacombs_to_moss_2": "Ichor Refinery Flag",
    "pickup_flag_rm_moss_top_hidden_4": "Flatlands Flag",
    "pickup_flag_rm_sea_mid_right_1": "Mountainside Flag",
    "pickup_flag_rm_mount_shortcut": "Smoked Forest Flag",
    "pickup_star_rm_forest_boss": "Living Quarters Titania Piece",
    "pickup_star_rm_mount_boss": "Smoked Forest Titania Piece",
    "pickup_star_rm_test_boss": "Flatlands Titania Piece",
    "pickup_star_rm_lake_boss": "Lake Titania Piece",
    "pickup_star_rm_sea_boss": "Mountainside Titania Piece",
    "pickup_star_rm_catacombs_boss": "Ichor Refinery Titania Piece",
    "pickup_star_rm_lab_boss": "Lab Titania Piece",
    "Titania_Piece": "Living Quarters Titania Piece (Head)",
    "Grenade": "Snowy Outpost Grenade",
    "Charge_Jump": "Factory Roof Charge Jump",
    "Grappling_Hook": "Flatlands Grappling Hook",
    "Grappling_Hook_Upgrade": "Living Quarters Grappling Hook Upgrade",
    "Infinite_Grapple": "Elfame Infinite Grapple",
    "pickup_dmg_rm_mount_right_4": "Smoked Forest Fae Silver (Top Right)",
    "pickup_dmg_rm_underhang_extra_1": "Barrows Ceiling Fae Silver",
    "pickup_dmg_rm_lake_hidden_5": "Lake Fae Silver (Right)",
    "pickup_dmg_rm_sea_mid_left_1": "Mountainside Fae Silver (Bottom)",
    "pickup_dmg_rm_lake_hidden_1": "Lake Fae Silver (Left)",
    "pickup_dmg_rm_lab_bleft_0": "Lab Fae Silver (Left)",
    "pickup_dmg_rm_forest_branch_2_2": "Living Quarters Fae Silver (Bottom Left)",
    "pickup_dmg_rm_forest_branch_2_6": "Living Quarters Fae Silver (Top Right)",
    "pickup_dmg_rm_catacombs_extra_2": "Ichor Refinery Fae Silver (Bottom Right)",
    "pickup_dmg_rfae_h1": "Elfame Fae Silver (Left)",
    "pickup_dmg_rm_mount_3_alt_hidden": "Smoked Forest Fae Silver (Bottom Left)",
    "pickup_dmg_rm_lab_save_right_2": "Lab Fae Silver (Right)",
    "pickup_dmg_rm_catacombs_extra_4_alt": "Ichor Refinery Fae Silver (Top Left)",
    "pickup_dmg_rm_sea_new_2_alt": "Mountainside Fae Silver (Top)",
    "pickup_dmg_rm_lab_to_boss_4": "Lab Fae Silver (Middle)",
    "pickup_dmg_rfae_h2": "Elfame Fae Silver (Right)",
    "pickup_dmg_rfae_h4": "Elfame Fae Silver (Middle)",





}   
    